// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SearchAgent(arg1:string,arg2:app.AgentKind):Promise<Array<app.Agent>>;
