// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function SearchAgent(arg1, arg2) {
  return window['go']['app']['App']['SearchAgent'](arg1, arg2);
}
