// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CreateRecord(arg1:app.Record):Promise<app.Record>;

export function DeleteRecord(arg1:app.Record):Promise<void>;

export function SearchAgent(arg1:string,arg2:app.AgentKind):Promise<Array<app.Agent>>;

export function SearchByClass(arg1:string):Promise<Array<app.Agent>>;

export function SearchRecordsByDay(arg1:string,arg2:app.AgentKind):Promise<Array<app.Record>>;
