// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRecord(arg1) {
  return window['go']['app']['App']['CreateRecord'](arg1);
}

export function DeleteRecord(arg1) {
  return window['go']['app']['App']['DeleteRecord'](arg1);
}

export function SearchAgent(arg1, arg2) {
  return window['go']['app']['App']['SearchAgent'](arg1, arg2);
}

export function SearchByClass(arg1) {
  return window['go']['app']['App']['SearchByClass'](arg1);
}

export function SearchRecordsByDay(arg1, arg2) {
  return window['go']['app']['App']['SearchRecordsByDay'](arg1, arg2);
}
