// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Goodbye(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SearchStudent(arg1:string):Promise<Array<app.Student>>;
