// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Goodbye(arg1) {
  return window['go']['app']['App']['Goodbye'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function SearchStudent(arg1) {
  return window['go']['app']['App']['SearchStudent'](arg1);
}
